// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Login.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::Task2;

class LoginHandler : virtual public LoginIf {
 public:
  LoginHandler() {
    // Your initialization goes here
  }

  void logIn(const std::string& userName, const int32_t key) {
    // Your implementation goes here
    printf("logIn\n");
  }

  void logOut() {
    // Your implementation goes here
    printf("logOut\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<LoginHandler> handler(new LoginHandler());
  ::std::shared_ptr<TProcessor> processor(new LoginProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

